//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub mod prelude;

pub mod ingredient_units;
pub mod ingredients;
pub mod recipes;
pub mod recipes_tags;
pub mod steps;
pub mod steps_ingridients;
pub mod tags;
pub mod users;
