//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub mod prelude;

pub mod ingredients;
pub mod recipes;
pub mod recipes_tags;
pub mod schema_migrations;
pub mod steps;
pub mod steps_ingridients;
pub mod tags;
pub mod users;
