//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub use super::ingredient_units::Entity as IngredientUnits;
pub use super::ingredients::Entity as Ingredients;
pub use super::recipes::Entity as Recipes;
pub use super::recipes_tags::Entity as RecipesTags;
pub use super::schema_migrations::Entity as SchemaMigrations;
pub use super::steps::Entity as Steps;
pub use super::steps_ingridients::Entity as StepsIngridients;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
