//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use std::{ffi::OsStr, path::Path};

use async_graphql::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Enum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(4))")]
pub enum Role {
    #[sea_orm(string_value = "root")]
    Root,
    #[sea_orm(string_value = "user")]
    User,
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "users")]
#[graphql(complex, concrete(name = "User", params()))]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub email: String,
    pub active: bool,
    pub encrypted_password: Option<String>,
    #[graphql(skip)]
    pub avatar: Option<String>,
    pub name: Option<String>,
    pub role: Role,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, Serialize, Deserialize, SimpleObject)]
#[graphql(concrete(name = "UserAvatar", params()))]
pub struct AvatarVariants {
    pub thumb: String,
    pub original: String,
}

fn get_extension_from_filename(filename: &str) -> Option<&str> {
    Path::new(filename).extension().and_then(OsStr::to_str)
}

#[ComplexObject]
impl Model {
    pub async fn avatar(&self) -> Option<AvatarVariants> {
        let ext = get_extension_from_filename(self.avatar.as_ref()?).or(Some("jpg"))?;

        self.avatar.as_ref().map(|_| AvatarVariants {
            thumb: format!("/avatars/{}/thumbnail.{}", self.id, ext),
            original: format!("/pictures/{}/original.{}", self.id, ext),
        })
    }
}
